export const INITIAL_TASKS = [
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "תיעוד וסגירה",
    "task": "צילום הדירה שלא נקבל הפתעות",
    "priority": "גבוה",
    "timing": "לפני מסירה",
    "source": "מקורי",
    "id": 1,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "בטחונות ומסמכים",
    "task": "לקחת מבעלת הדירה הנוכחית שטר חוב על סך 75 אלף",
    "priority": "גבוה",
    "timing": "לפני סגירה",
    "source": "מקורי",
    "id": 2,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "בטחונות ומסמכים",
    "task": "לקחת / להסדיר ערבויות מול בעלת הדירה הנוכחית",
    "priority": "גבוה",
    "timing": "לפני סגירה",
    "source": "מקורי",
    "id": 3,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "בטחונות ומסמכים",
    "task": "לקחת שיקים לכל החשבונות שהיו: חשמל, מים, ארנונה",
    "priority": "גבוה",
    "timing": "לפני סגירה",
    "source": "מקורי",
    "id": 4,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "מה נשאר בדירה",
    "task": "להחליט / לתאם האם משאירים ארונות",
    "priority": "בינוני",
    "timing": "לפני מעבר",
    "source": "מקורי",
    "id": 5,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "מה נשאר בדירה",
    "task": "להחליט / לתאם האם משאירים מדיח",
    "priority": "בינוני",
    "timing": "לפני מעבר",
    "source": "מקורי",
    "id": 6,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "ניתוקים",
    "task": "לנתק חשמל מהשם שלי",
    "priority": "גבוה",
    "timing": "סמוך לעזיבה",
    "source": "מקורי",
    "id": 7,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "ניתוקים",
    "task": "לנתק מים מהשם שלי",
    "priority": "גבוה",
    "timing": "סמוך לעזיבה",
    "source": "מקורי",
    "id": 8,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "ניתוקים",
    "task": "לנתק ארנונה מהשם שלי",
    "priority": "גבוה",
    "timing": "סמוך לעזיבה",
    "source": "מקורי",
    "id": 9,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "ניתוקים",
    "task": "לנתק / לסגור ועד בית",
    "priority": "גבוה",
    "timing": "סמוך לעזיבה",
    "source": "מקורי",
    "id": 10,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "מול יפה",
    "task": "יפה — לעדכן עד 14.5 אם יש מחליפים או אין",
    "priority": "גבוה",
    "timing": "14.5",
    "source": "מקורי",
    "id": 11,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "תיקונים",
    "task": "לבדוק אם צריך לצבוע דירה או שיפה אמרה שנסתדר",
    "priority": "בינוני",
    "timing": "לפני מסירה",
    "source": "מקורי",
    "id": 12,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "תיקונים",
    "task": "ממ״ד — לתקן סגירה",
    "priority": "בינוני",
    "timing": "לפני מסירה",
    "source": "מקורי",
    "id": 13,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "תיקונים",
    "task": "מטבח — להחליף מנורה קטנה פאן",
    "priority": "נמוך",
    "timing": "לפני מסירה",
    "source": "מקורי",
    "id": 14,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "old",
    "areaLabel": "דירה נוכחית",
    "category": "תיקונים",
    "task": "ברז כיור חדר שינה — יצא מהמקום",
    "priority": "נמוך",
    "timing": "לפני מסירה",
    "source": "מקורי",
    "id": 15,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "ליאם / מסגרת",
    "task": "בייבי קלאב — להעביר לסניף החדש; אמרו ב־13.5 שיש מקום",
    "priority": "גבוה",
    "timing": "בהקדם",
    "source": "מקורי",
    "id": 16,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "חוזה ותשלומים",
    "task": "מאיר בעל דירה — ממתין לחוזה סופי",
    "priority": "גבוה",
    "timing": "בהקדם",
    "source": "מקורי",
    "id": 17,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "חוזה ותשלומים",
    "task": "אייל — ממתין לגבי דמי תיווך כמה",
    "priority": "גבוה",
    "timing": "בהקדם",
    "source": "מקורי",
    "id": 18,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "תאריכים",
    "task": "חוזה בדירה קיימת נגמר ב־15.6",
    "priority": "גבוה",
    "timing": "תזכורת",
    "source": "מקורי",
    "id": 19,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "תאריכים",
    "task": "דירה חדשה ניתן להיכנס כבר ב־1.6",
    "priority": "גבוה",
    "timing": "תזכורת",
    "source": "מקורי",
    "id": 20,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "רואת חשבון",
    "task": "עדכונים למס הכנסה, ביטוח לאומי וכל מה שקשור במעבר דירה",
    "priority": "בינוני",
    "timing": "אחרי חוזה",
    "source": "מקורי",
    "id": 21,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "רואת חשבון",
    "task": "לשאול אם אפשר לקבל החזרים על דמי תיווך, שכר דירה וכו׳",
    "priority": "בינוני",
    "timing": "אחרי חוזה",
    "source": "מקורי",
    "id": 22,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "דוחות",
    "task": "בדוחות לשנות את העלויות החדשות של כל הדירה החדשה",
    "priority": "בינוני",
    "timing": "אחרי חוזה",
    "source": "מקורי",
    "id": 23,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "שינוי כתובת",
    "task": "כתובת דואר — לשנות לאזור החדש",
    "priority": "בינוני",
    "timing": "אחרי מעבר",
    "source": "מקורי",
    "id": 24,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "שינוי כתובת",
    "task": "אוטו / רכב — לשנות לאזור החדש",
    "priority": "בינוני",
    "timing": "אחרי מעבר",
    "source": "מקורי",
    "id": 25,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "שינוי כתובת",
    "task": "תושב / משרד הפנים — לשנות לאזור החדש",
    "priority": "בינוני",
    "timing": "אחרי מעבר",
    "source": "מקורי",
    "id": 26,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "הובלה",
    "task": "מובילים + פירוק והרכבה — להתחיל לחפש ולבדוק מה עושים",
    "priority": "גבוה",
    "timing": "בהקדם",
    "source": "מקורי",
    "id": 27,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "חוזה ותשלומים",
    "task": "להכין 12 צ׳קים לדירה החדשה",
    "priority": "גבוה",
    "timing": "לפני חתימה/כניסה",
    "source": "מקורי",
    "id": 28,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "חוזה ותשלומים",
    "task": "להכין צ׳ק ביטחון / שטר חוב / ערבויות",
    "priority": "גבוה",
    "timing": "לפני חתימה/כניסה",
    "source": "מקורי",
    "id": 29,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "לפני כניסה",
    "task": "חברת ניקיון לדירה החדשה",
    "priority": "גבוה",
    "timing": "לפני 1.6",
    "source": "מקורי",
    "id": 30,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "לפני כניסה",
    "task": "ריסוס לדירה החדשה",
    "priority": "גבוה",
    "timing": "לפני 1.6",
    "source": "מקורי",
    "id": 31,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "לפני כניסה",
    "task": "לראות שיש מנעול חדש",
    "priority": "גבוה",
    "timing": "לפני כניסה",
    "source": "מקורי",
    "id": 32,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "לפני כניסה",
    "task": "אמר שיש רשתות כבר — לבדוק בפועל",
    "priority": "בינוני",
    "timing": "לפני כניסה",
    "source": "מקורי",
    "id": 33,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "לפני כניסה",
    "task": "לבדוק כיריים",
    "priority": "בינוני",
    "timing": "לפני כניסה",
    "source": "מקורי",
    "id": 34,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "לפני כניסה",
    "task": "לבדוק מנורות בכל הבית",
    "priority": "בינוני",
    "timing": "לפני כניסה",
    "source": "מקורי",
    "id": 35,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "לפני כניסה",
    "task": "לדבר מול אשתו לגבי רשתות / כיריים / מנורות",
    "priority": "בינוני",
    "timing": "לפני כניסה",
    "source": "מקורי",
    "id": 36,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "התקנות",
    "task": "להזמין את יניב להתקין הכל על הקירות או לבקש מהמובילים",
    "priority": "בינוני",
    "timing": "אחרי כניסה",
    "source": "מקורי",
    "id": 37,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "קניות שימושיות",
    "task": "דייסון או סוג של שואב חדש לבית",
    "priority": "נמוך",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 38,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "תשתיות",
    "task": "להעביר את סלקום לדירה החדשה — אינטרנט והכל",
    "priority": "גבוה",
    "timing": "לפני/ביום כניסה",
    "source": "מקורי",
    "id": 39,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "אריזות",
    "task": "לחפש קרטונים להתחיל לארוז",
    "priority": "גבוה",
    "timing": "עכשיו",
    "source": "מקורי",
    "id": 40,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "שינוי כתובת",
    "task": "קופת חולים — להעביר לכתובת החדשה",
    "priority": "בינוני",
    "timing": "אחרי מעבר",
    "source": "מקורי",
    "id": 41,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "שינוי כתובת",
    "task": "סלקום — להעביר לכתובת החדשה",
    "priority": "בינוני",
    "timing": "אחרי/לפני מעבר",
    "source": "מקורי",
    "id": 42,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "שינוי כתובת",
    "task": "משרד הפנים — להעביר לכתובת החדשה",
    "priority": "בינוני",
    "timing": "אחרי מעבר",
    "source": "מקורי",
    "id": 43,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "שינוי כתובת",
    "task": "כרטיסי אשראי — להעביר לכתובת החדשה",
    "priority": "בינוני",
    "timing": "אחרי מעבר",
    "source": "מקורי",
    "id": 44,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "בדיקות לפני כניסה",
    "task": "לצלם מצב דירה חדשה לפני כניסה",
    "priority": "גבוה",
    "timing": "ביום קבלת מפתח",
    "source": "תוספת",
    "id": 45,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "בדיקות לפני כניסה",
    "task": "לצלם מוני מים/חשמל בכניסה",
    "priority": "גבוה",
    "timing": "ביום קבלת מפתח",
    "source": "תוספת",
    "id": 46,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "בדיקות לפני כניסה",
    "task": "לבדוק מים חמים, לחץ מים ונזילות",
    "priority": "בינוני",
    "timing": "לפני/ביום כניסה",
    "source": "תוספת",
    "id": 47,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "בדיקות לפני כניסה",
    "task": "לבדוק חשמל, מזגנים, תריסים וחלונות",
    "priority": "בינוני",
    "timing": "לפני/ביום כניסה",
    "source": "תוספת",
    "id": 48,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "בטיחות",
    "task": "לבדוק ביטוח דירה / צד ג׳",
    "priority": "בינוני",
    "timing": "אחרי חוזה",
    "source": "תוספת",
    "id": 49,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "אריזות",
    "task": "לסמן קרטונים לפי חדרים",
    "priority": "בינוני",
    "timing": "בזמן אריזה",
    "source": "תוספת",
    "id": 50,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "new",
    "areaLabel": "דירה חדשה",
    "category": "אריזות",
    "task": "להכין קרטון לילה ראשון",
    "priority": "גבוה",
    "timing": "לפני הובלה",
    "source": "תוספת",
    "id": 51,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "ליאם",
    "task": "ליאם — מיטה חדשה או לראות שאפשר להנמיך",
    "priority": "בינוני",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 52,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "ליאם",
    "task": "חסימת מגירות / הגנת שקעים — ליאם",
    "priority": "גבוה",
    "timing": "לפני/מיד אחרי כניסה",
    "source": "מקורי",
    "id": 53,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "סלון",
    "task": "מזנון חדש",
    "priority": "נמוך",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 54,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "אחסון",
    "task": "ארונות",
    "priority": "נמוך",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 55,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "סלון",
    "task": "טלוויזיה נוספת לסלון",
    "priority": "נמוך",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 56,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "מרפסת",
    "task": "ריהוט למרפסת",
    "priority": "נמוך",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 57,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "מרפסת",
    "task": "מנגל",
    "priority": "נמוך",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 58,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  },
  {
    "area": "shopping",
    "areaLabel": "קניות",
    "category": "תאורה",
    "task": "תאורה נוספת תחתונה",
    "priority": "נמוך",
    "timing": "בהמשך",
    "source": "מקורי",
    "id": 59,
    "status": "לא התחיל",
    "noteOpen": false,
    "owner": "",
    "notes": ""
  }
];
